name: Bulk Generate Articles

on:
  workflow_dispatch:
    inputs:
      file:
        description: Ruta del YAML con tópicos
        required: false
        default: content/topics.yml

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate all articles listed in YAML
        run: |
          python - << 'PY'
          import os, sys, yaml, subprocess
          path = os.environ.get('TOPICS_FILE') or '${{ github.event.inputs.file }}' or 'content/topics.yml'
          with open(path, 'r', encoding='utf-8') as f:
              data = yaml.safe_load(f) or []
          def run(topic, style, accent, details, category):
              cmd = [
                  sys.executable,
                  'tools/generate_article.py',
                  '--topic', topic,
                  '--style', style or 'fotográfico',
                  '--accent', accent or 'azul',
              ]
              if details:
                  cmd += ['--details', details]
              if category:
                  cmd += ['--category', category]
              print('>>', ' '.join(cmd))
              subprocess.check_call(cmd)
          for item in data:
              run(
                  item.get('topic','').strip(),
                  item.get('style','fotográfico'),
                  item.get('accent','azul'),
                  item.get('details',''),
                  item.get('category')
              )
          PY

      - name: Create Pull Request with generated content
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(content): bulk generated articles from topics.yml"
          title: "chore(content): bulk generated articles from topics.yml"
          body: |
            This PR contains articles and images generated by the bulk generation workflow from `content/topics.yml`.
          branch: "content/generated-${{ github.run_id }}"
          delete-branch: true
          add-paths: |
            content/blog/**
            public/images/blog/**

